[package]
name = "lumi_parser"
version = "0.1.0"
edition = "2021"
description = "Parser for Lumi programming language"
license = "MIT"

[dependencies]
lumi_ast = { path = "../lumi_ast" }
lumi_lexer = { path = "../lumi_lexer" }
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"